services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser-s2
    volumes:
      - /root:/srv
      - /opt/filebrowser-s2/filebrowser.db:/database/filebrowser.db
      - /opt/filebrowser-s2/settings.json:/config/settings.json
    ports:
      - "8098:80"
    restart: unless-stopped
